import * as path from "path";
import * as fs from "fs";

/**
 * Interface representing the compiled WebAssembly module bindings generated by wasm-pack
 * for the cognee-rs engine.
 */
export interface CogneeWasmEngine {
  init_engine(configJson: string): Promise<void>;
  remember(text: string, sessionId?: string): Promise<void>;
  recall(query: string, sessionId?: string): Promise<string[]>;
  forget(datasetName: string): Promise<void>;
  improve(feedbackJson: string): Promise<void>;
  extract_code_graph(filePath: string, fileContent: string): Promise<string>;
}

export interface CogneeWasmConfig {
  llmApiKey: string;
  llmModel?: string;
  llmEndpoint?: string;
  embeddingProvider?: "openai" | "onnx" | "ollama";
  embeddingModel?: string;
  dbPath?: string;
}

/**
 * Singleton background service manager that loads, instantiates, and manages the lifecycle
 * of the cognee-rs WebAssembly (WASM) compiled module inside Continue's Node.js runtime.
 *
 * Running in WASM provides several massive benefits:
 * 1. Zero platform compilation/binary issues (Gatekeeper, Windows SmartScreen).
 * 2. Runs inside VS Code's extension sandbox with high-performance Rust parallel processing.
 * 3. Zero local Python dependencies or setup requirements on the user's OS.
 */
export class CogneeWasmService {
  private static instance: CogneeWasmService | null = null;
  private engine: CogneeWasmEngine | null = null;
  private isInitialized = false;

  private constructor() {}

  public static getInstance(): CogneeWasmService {
    if (!CogneeWasmService.instance) {
      CogneeWasmService.instance = new CogneeWasmService();
    }
    return CogneeWasmService.instance;
  }

  /**
   * Dynamically loads and initializes the compiled WebAssembly bindings.
   * Supports standard node-side loading of local `.wasm` files bundled in the extension.
   */
  public async initialize(config: CogneeWasmConfig, extensionPath: string): Promise<void> {
    if (this.isInitialized) {
      return;
    }

    try {
      // 1. Resolve paths to the bundled wasm-pack build folder
      const wasmPkgPath = path.join(extensionPath, "bin", "cognee-rs-wasm");
      const wasmBindingFile = path.join(wasmPkgPath, "cognee_rs_wasm.js");

      if (!fs.existsSync(wasmBindingFile)) {
        throw new Error(
          `Cognee WASM bindings not found at ${wasmBindingFile}. Make sure to compile the rust project with 'wasm-pack' first.`
        );
      }

      // 2. Dynamically import the WASM JS wrapper generated by wasm-pack
      // Under Node.js/CommonJS runtimes, wasm-pack can be loaded natively
      const wasmBindings = await import(wasmBindingFile);

      // 3. Set up the local SQLite / LanceDB data directories inside the extension storage
      const defaultDbPath = config.dbPath || path.join(extensionPath, "out", "cognee_memory.db");
      const resolvedConfig: CogneeWasmConfig = {
        llmApiKey: config.llmApiKey,
        llmModel: config.llmModel || "openai/gpt-5-mini",
        llmEndpoint: config.llmEndpoint || "https://api.openai.com/v1",
        embeddingProvider: config.embeddingProvider || "openai",
        embeddingModel: config.embeddingModel || "text-embedding-3-small",
        dbPath: defaultDbPath,
      };

      // 4. Instantiate and initialize the memory engine
      this.engine = wasmBindings as CogneeWasmEngine;
      await this.engine.init_engine(JSON.stringify(resolvedConfig));

      this.isInitialized = true;
      console.log("Cognee WASM Memory Engine successfully initialized.");
    } catch (error) {
      console.error("Failed to initialize Cognee WASM Service:", error);
      throw error;
    }
  }

  /**
   * Helper to ensure service is ready before invoking operations
   */
  private ensureReady(): CogneeWasmEngine {
    if (!this.isInitialized || !this.engine) {
      throw new Error("Cognee WASM Service is not initialized. Call initialize() first.");
    }
    return this.engine;
  }

  /**
   * Ingest and build graph memory for a document or code snippet.
   */
  public async remember(text: string, sessionId?: string): Promise<void> {
    const engine = this.ensureReady();
    await engine.remember(text, sessionId);
  }

  /**
   * Query the unified vector-graph memory with auto-routing search strategies.
   */
  public async recall(query: string, sessionId?: string): Promise<string[]> {
    const engine = this.ensureReady();
    return await engine.recall(query, sessionId);
  }

  /**
   * Clean up dataset artifacts.
   */
  public async forget(datasetName: string): Promise<void> {
    const engine = this.ensureReady();
    await engine.forget(datasetName);
  }

  /**
   * Incorporate agent execution traces or user feedback to refine the graph weights.
   */
  public async improve(feedback: any): Promise<void> {
    const engine = this.ensureReady();
    await engine.improve(JSON.stringify(feedback));
  }

  /**
   * Leverage tree-sitter AST nodes to extract files, classes, import relationships, and functions.
   */
  public async extractCodeGraph(filePath: string, fileContent: string): Promise<any> {
    const engine = this.ensureReady();
    const resultJson = await engine.extract_code_graph(filePath, fileContent);
    return JSON.parse(resultJson);
  }
}
